name: Acceptance tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos6
          - centos7
          - debian8
          - debian9
          - debian10
        puppet:
          - "6"
          - "5"
    name: ${{ matrix.distro }} Puppet ${{ matrix.puppet }}
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.5"
          architecture: 'x64'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --without development
      - name: Run tests
        run: bundle exec rake beaker
        env:
          BEAKER_PUPPET_COLLECTION: puppet${{ matrix.puppet }}
          BEAKER_setfile: ${{ matrix.distro }}-64{hostname=${{ matrix.distro }}-64.example.com}
